# **Clasificacion de accines de usuarios en una plataforma de videojuego**

## Objetivos
- Comprender el uso del aprendizaje supervisado para clasificar acciones de usuarios en entornos digitales
- Identificar patrones de comportamiento en plataformas de videojuegos
- Aplicar reglas simples para categorizar acciones utilizando python
  
## Creacion de datos

In [3]:
datos = [
    ["user01", "Combate", 120 , "Victoria"],
    ["user02", "Exploracion", 300, "Descubrimiento"],
    ["user03", "Interaccion social", 180, "Mensaje enviado"],
    ["user04", "Combate", 90, "Derrota"],
    ["user05", "Exploracion", 240, "Sin hallazgos"]
   ]

---
## Creacion dataframe

In [4]:
import pandas as pd

df = pd.DataFrame(datos,
columns = ["Usuario", "Accion", "Duracion", "Resultado"]
) 
df

  Usuario              Accion  Duracion        Resultado
0  user01             Combate       120         Victoria
1  user02         Exploracion       300   Descubrimiento
2  user03  Interaccion social       180  Mensaje enviado
3  user04             Combate        90          Derrota
4  user05         Exploracion       240    Sin hallazgos

----
### Analisis de los datos:

- Accion: Indica la accion que realiza cada usuario en la plataforma de videojuegos
- Duracion: Indica cuanto tiempo duro la actividad
- Resultado: Indica que ocurrio durante la accion
  
Para realizar la clasificacion voy a usar principalmente las variables Accion y Resultado

In [6]:
# Resumen de los datos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Usuario    5 non-null      object
 1   Accion     5 non-null      object
 2   Duracion   5 non-null      int64
 3   Resultado  5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

----
## Reglas de clasificacion

Utilizare las siguientes reglas:

1. Si la accion es Combate y el resultado es Victoria -> Combate exitoso
2. Si la accion es Combate y el resultado es Derrota -> Combate fallido
3. Si la accion es Exploracion y el resultado es Descubrimiento -> Exploracion exitosa
4. Si la accion es Exploracion y el resultado es Sin hallazgos -> Exploracion sin exito
5. Si la accion es Interaccion social y el resultado Mensaje enviado -> Interaccion social exitosa

---
## Programacion de las reglas

In [9]:
# Funcion para clasificar
def clasificar(accion, resultado):
    if accion == "Combate" and resultado == "Victoria":
        return "Combate exitoso"
    elif accion == "Combate" and resultado == "Derrota":
        return "Combate fallido"
    elif accion == "Exploracion" and resultado == "Descubrimiento":
        return "Exploracion exitosa"
    elif accion == "Exploracion" and resultado == "Sin hallazgos":
        return "Exploracion sin exito"
    elif accion == "Interaccion social" and resultado == "Mensaje enviado":
        return "Interaccion social exitosa"
    else: 
        return "No clasificado"

## Aplicar a los datos

In [11]:
df["Clasificacion"] = df.apply(lambda fila: clasificar(
    fila["Accion"],
    fila["Resultado"]
), axis=1
)

df

,Usuario,Accion,Duracion,Resultado,Clasificacion
0,user01,Combate,120,Victoria,Combate exitoso
1,user02,Exploracion,300,Descubrimiento,Exploracion exitosa
2,user03,Interaccion social,180,Mensaje enviado,Interaccion social exitosa
3,user04,Combate,90,Derrota,Combate fallido
4,user05,Exploracion,240,Sin hallazgos,Exploracion sin exito

----

1. **¿Que reglas funcionaron mejor para clasificar las acciones?**
- Las reglas que funcionaron mejor fueron las que utilizaron las variables Accion y Resultado, ya que permitieron clasificar  
  las acciones segun lo que realizo el usuario y lo que ocurrio como consecuencia

2. **¿Que limitaciones tiene este enfoque basado en reglas?**
- Una de las principales limitaciones es que la clasificacion solo funciona para los casos contemplados en las reglas.  
  Si aparece una accion o un resultado nuevo que no fue considerado el sistema podria no saber como clasificarlo

3. **¿Como se podria mejorar la clasificacion utilizando modelos de Machine Learning mas avanzados?**
- Se podria entrenar un modelo de Machine Learning con una mayor cantidad de casos previamente clasificados.  
  De esta manera, el modelo podria aprender patrones de los datos y realizar clasificaciones sobre casos nuevos sin tener que definir  
  manualmente una regla para cada situacion

----

### Observaciones del estudiante

En esta actividad comprendi como se pueden utilizar reglas simples para clasificar acciones de usuarios a partir de diferentes caracteristicas de los datos.  
Tambien observe que este enfoque puede funcionar para casos sencillos pero tiene limitaciones cuando aparecen datos nuevos que no fueron contemplados en las reglas.  
Esto me permitio entender la importancia del aprendizaje supervisado y como un modelo de Machine Learning podria aprender patrones a partir de ejemplos